from __future__ import annotations


def build_web_routes() -> tuple[str, ...]:
    return (
        "/", "RootHandler",
        "/auth/login", "AuthLoginHandler",
        "/auth/check", "AuthCheckHandler",
        "/auth/logout", "AuthLogoutHandler",
        "/message", "MessageHandler",
        "/upload", "UploadHandler",
        "/uploads/(.*)", "UploadsHandler",
        "/api/file", "FileServeHandler",
        "/poll", "PollHandler",
        "/stream", "StreamHandler",
        "/chat", "ChatHandler",
        "/config", "ConfigHandler",
        "/api/channels", "ChannelsHandler",
        "/api/weixin/qrlogin", "WeixinQrHandler",
        "/api/tools", "ToolsHandler",
        "/api/skills", "SkillsHandler",
        "/api/memory", "MemoryHandler",
        "/api/memory/content", "MemoryContentHandler",
        "/api/knowledge/list", "KnowledgeListHandler",
        "/api/knowledge/read", "KnowledgeReadHandler",
        "/api/knowledge/graph", "KnowledgeGraphHandler",
        "/api/platform/tenant-user-meta", "PlatformTenantUserMetaHandler",
        "/api/platform/tenants", "PlatformTenantsHandler",
        "/api/platform/tenants/(.*)", "PlatformTenantDetailHandler",
        "/api/platform/tenant-users", "PlatformTenantUsersHandler",
        "/api/platform/tenant-users/(.*)/(.*)", "PlatformTenantUserDetailHandler",
        "/api/platform/tenant-user-identities", "PlatformTenantUserIdentitiesHandler",
        "/api/platform/tenant-user-identities/(.*)/(.*)/(.*)", "PlatformTenantUserIdentityDetailHandler",
        "/api/platform/agents", "PlatformAgentsHandler",
        "/api/platform/agents/(.*)", "PlatformAgentDetailHandler",
        "/api/platform/bindings", "PlatformBindingsHandler",
        "/api/platform/bindings/(.*)", "PlatformBindingDetailHandler",
        "/api/agents", "AgentsHandler",
        "/api/bindings", "BindingsHandler",
        "/api/scheduler", "SchedulerHandler",
        "/api/sessions", "SessionsHandler",
        "/api/sessions/(.*)/generate_title", "SessionTitleHandler",
        "/api/sessions/(.*)/clear_context", "SessionClearContextHandler",
        "/api/sessions/(.*)", "SessionDetailHandler",
        "/api/history", "HistoryHandler",
        "/api/logs", "LogsHandler",
        "/api/mcp/servers", "MCPServersHandler",
        "/api/mcp/servers/test", "MCPServersTestHandler",
        "/api/mcp/servers/(.*)/tools", "MCPServerToolsHandler",
        "/api/version", "VersionHandler",
        "/assets/(.*)", "AssetsHandler",
    )
